@startuml
boundary InGameView
control GameController

== 윷 던지기 시작 ==
InGameView -> GameController: rollingYut()
note right: “윷 던지기” 버튼 클릭 시 호출
activate GameController

GameController --> InGameView: disableYutButton()
note left: 중복 클릭 방지 위해 버튼 비활성화
deactivate GameController
@enduml
